set -g prefix C-a
unbind C-b
bind-key C-a send-prefix
setw -g window-status-current-format "#[reverse] #I:#W"

set -g pane-border-style "fg=#5c6370"
set -g pane-active-border-style "fg=#e5c07b"
set -g pane-border-status top
set -g pane-border-format " #{?pane_active,#{pane_index} #{pane_current_command},} "

setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1

bind c new-window -c "#{pane_current_path}"
bind Space last-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# prefix + Ctrl-s - save
# prefix + Ctrl-r - restore
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'

set -g @plugin 'wfxr/tmux-fzf-url'
