set -g prefix C-a
unbind C-b
bind-key C-a send-prefix
setw -g window-status-current-format "#[reverse] #I:#W"

set -g base-index 1
setw -g pane-base-index 1
bind c new-window -c "#{pane_current_path}"
bind Space last-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'

# prefix + Ctrl-s - save
# prefix + Ctrl-r - restore

set -g @plugin 'wfxr/tmux-fzf-url'
